# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        entidad:
            entity:
              class: AppBundle\Entity\Profesor
              property: dni

    encoders:
      AppBundle\Entity\Profesor: bcrypt

    role_hierarchy:
      ROLE_ADMIN: [ROLE_TUTOR]
      ROLE_TUTOR: [ROLE_PROFESOR]
      ROLE_PROFESOR: [ROLE_USER]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
              login_path: entrar
              check_path: comprobar

            logout:
              path: salir
              target: inicio

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
