# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        manuales:
            memory:
              users:
                administrador:
                  password: botijo
                  roles: 'ROLE_ADMIN'
                usuario:
                  password: pollo
                  roles: 'ROLE_USER'
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        proteger_borrado:
                  pattern: ^/alumnos/eliminar
                  http_basic: ~

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
